# fly.toml file generated for shaun-flex-stable-3 on 2023-01-24T10:42:59-06:00


kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PRIMARY_REGION = "ord"

[checks]
  [checks.pg]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/pg"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.vm]
    grace_period = "1s"
    interval = "1m"
    method = "get"
    path = "/flycheck/vm"
    port = 5500
    timeout = "10s"
    type = "http"

  [checks.role]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/flycheck/role"
    port = 5500
    timeout = "10s"
    type = "http"

[[services]]
  internal_port = 5432 # Postgres instance
  protocol = "tcp"

[[services.ports]]
  handlers = ["pg_tls"]
  port = 5432


[[mounts]]
  destination = "/data"
  source = "pg_data"

[metrics]
  path = "/metrics"
  port = 9187
